name: Nightly Build
run-name: "Nightly Build (${{ github.ref_name }})"

on:
  workflow_dispatch:
  schedule:
  # NOTE - changes to the cron spec should be pushed by https://github.com/quic-yocto-ci
  # so that build notification emails will be sent out properly.
  # At 0:22 UTC everyday - picked a random "minute" as top of hour can be busy in github
  - cron: "22 0 * * *"

permissions:
  contents: read

jobs:
  build-nightly:
    permissions:
      contents: read
      packages: read
      actions: read
    uses: ./.github/workflows/build-yocto.yml
    with:
      skip_if_github_cached: true
    secrets: inherit
